#!/bin/bash
# Quick Railway Deployment Setup Script

echo "🚀 Spaza Track - Railway.app Deployment"
echo "======================================="
echo ""
echo "This script assumes you have:"
echo "✅ GitHub repo created"
echo "✅ Code pushed to https://github.com/sibusis-code/spaza-track"
echo ""
echo "Next steps:"
echo "1. Go to https://railway.app"
echo "2. Click 'New Project' → 'Deploy from GitHub'"
echo "3. Select: sibusis-code/spaza-track"
echo "4. Wait for build"
echo "5. Go to 'Variables' and add:"
echo ""
echo "   DATABASE_URL=sqlite:///./spaza.db"
echo "   SECRET_KEY=your-random-secret-key"
echo "   ALGORITHM=HS256"
echo "   ACCESS_TOKEN_EXPIRE_MINUTES=10080"
echo "   CORS_ORIGINS=https://sibusis-code.github.io/spaza-track"
echo ""
echo "6. Click the service → Settings"
echo "7. Set 'Root Directory' to: backend"
echo "8. Redeploy"
echo ""
echo "Then create admin user via Railway terminal:"
echo "   python backend/create_admin.py"
echo ""
